import { Unit, Room, Booking, AppNotification, AuditLog } from '../types';

export const INITIAL_UNITS: Unit[] = [
  {
    id: 'unit_sekretariat',
    nama_unit: 'Sekretariat BSKJI',
    kode_unit: 'SET',
    kepala_unit: 'Sekretaris BSKJI',
  },
  {
    id: 'unit_poptikji',
    nama_unit: 'POPTIKJI',
    kode_unit: 'POPTIKJI',
    kepala_unit: 'Kepala POPTIKJI',
  },
  {
    id: 'unit_p4si',
    nama_unit: 'P4SI',
    kode_unit: 'P4SI',
    kepala_unit: 'Kepala P4SI',
  },
  {
    id: 'unit_pih',
    nama_unit: 'PIH',
    kode_unit: 'PIH',
    kepala_unit: 'Kepala PIH',
  },
  {
    id: 'unit_p2si',
    nama_unit: 'P2SI',
    kode_unit: 'P2SI',
    kepala_unit: 'Kepala P2SI',
  },
];

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room_sinergi',
    nama_ruang: 'Ruang Sinergi',
    lokasi: 'Gedung Kementerian Perindustrian - Lantai 19',
    lantai: 19,
    kapasitas: 40,
    fasilitas: [],
    status: 'Aktif',
    keterangan: 'Ruang rapat utama kapasitas 40 orang dengan falisitas online meeting.',
    foto: 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?auto=format&fit=crop&w=800&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'room_digital',
    nama_ruang: 'Ruang Digital',
    lokasi: 'Gedung Kementerian Perindustrian - Lantai 19',
    lantai: 19,
    kapasitas: 20,
    fasilitas: [],
    status: 'Aktif',
    keterangan: 'Ruang rapat kapasitas 20 orang.',
    foto: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=800&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'room_inovatif',
    nama_ruang: 'Ruang Inovatif',
    lokasi: 'Gedung Kementerian Perindustrian - Lantai 19',
    lantai: 19,
    kapasitas: 10,
    fasilitas: [],
    status: 'Aktif',
    keterangan: 'Ruang rapat  kapasitas 10 orang dengan falisitas online meeting.',
    foto: 'https://images.unsplash.com/photo-1577412647305-991150c7d163?auto=format&fit=crop&w=800&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'room_industri_hijau',
    nama_ruang: 'Ruang Industri Hijau',
    lokasi: 'Gedung Kementerian Perindustrian - Lantai 20',
    lantai: 20,
    kapasitas: 25,
    fasilitas: [],
    status: 'Aktif',
    keterangan: 'Ruang rapat kapasitas 25 orang.',
    foto: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'room_standar',
    nama_ruang: 'Ruang Standar',
    lokasi: 'Gedung Kementerian Perindustrian - Lantai 20',
    lantai: 20,
    kapasitas: 20,
    fasilitas: [],
    status: 'Aktif',
    keterangan: 'Ruang rapat kapasitas 20 orang.',
    foto: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'room_produktif',
    nama_ruang: 'Ruang Produktif',
    lokasi: 'Gedung Kementerian Perindustrian - Lantai 19',
    lantai: 20,
    kapasitas: 10,
    fasilitas: [],
    status: 'Aktif',
    keterangan: 'Ruang rapat kapasitas 10 orang.',
    foto: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk_001',
    nomor_peminjaman: '0001/BSKJI.1/RT/RR/VIII/2026',
    user_id: 'usr_peminjam_01',
    peminjam_nama: 'Budi Santoso',
    peminjam_nip: '19850315 200801 1 002',
    peminjam_jabatan: 'Analis Kebijakan Ahli Muda',
    unit_id: 'unit_program',
    unit_nama: 'Bagian Program dan Evaluasi',
    room_id: 'room_sinergi',
    room_nama: 'Ruang Sinergi',
    keperluan: 'Rapat Koordinasi Penyusunan Rencana Kerja BSKJI 2027',
    tanggal: '2026-08-12',
    jam_mulai: '09:00',
    jam_selesai: '12:00',
    durasi: '3 Jam',
    jumlah_peserta: 25,
    keterangan: 'Membutuhkan projector 4K, microfon wireless 4 unit, dan fasilitas hybrid Zoom.',
    status: 'DISETUJUI',
    approvals: [
      {
        id: 'app_001_1',
        booking_id: 'bk_001',
        approver_id: 'usr_koordinator_01',
        approver_nama: 'Siti Rahma',
        approver_nip: '19820420 200604 2 003',
        approver_jabatan: 'Koordinator Urusan Internal dan Ruang Rapat',
        level_approval: 'KOORDINATOR',
        status: 'DISETUJUI',
        catatan: 'Ketersediaan ruangan sudah diverifikasi dan siap disiapkan teknisi BMN.',
        approved_at: '2026-08-10T10:20:00Z',
      },
      {
        id: 'app_001_2',
        booking_id: 'bk_001',
        approver_id: 'usr_kabag_01',
        approver_nama: 'Agus Setiawan',
        approver_nip: '19720910 199803 1 001',
        approver_jabatan: 'Kepala Bagian Umum',
        level_approval: 'KABAG',
        status: 'DISETUJUI',
        catatan: 'Disetujui akhir. Ruang terkunci untuk agenda ini.',
        approved_at: '2026-08-10T13:00:00Z',
      },
    ],
    check_in: {
      checked_in_at: '2026-08-12T08:50:00Z',
      checked_in_by: 'Budi Santoso',
    },
    created_at: '2026-08-10T08:30:00Z',
    updated_at: '2026-08-10T13:00:00Z',
  },
  {
    id: 'bk_002',
    nomor_peminjaman: '0002/BSKJI.1/RT/RR/VIII/2026',
    user_id: 'usr_peminjam_01',
    peminjam_nama: 'Budi Santoso',
    peminjam_nip: '19850315 200801 1 002',
    peminjam_jabatan: 'Analis Kebijakan Ahli Muda',
    unit_id: 'unit_program',
    unit_nama: 'Bagian Program dan Evaluasi',
    room_id: 'room_digital',
    room_nama: 'Ruang Digital',
    keperluan: 'Diskusi Teknis Pembahasan DPA BSKJI Tahap II',
    tanggal: '2026-08-13',
    jam_mulai: '13:00',
    jam_selesai: '15:30',
    durasi: '2 Jam 30 Menit',
    jumlah_peserta: 18,
    keterangan: 'Membawa laptop masing-masing, butuh TV HDMI cable.',
    status: 'MENUNGGU_PERSETUJUAN_KOORDINATOR',
    approvals: [],
    created_at: '2026-08-11T09:00:00Z',
    updated_at: '2026-08-11T09:00:00Z',
  },
  {
    id: 'bk_003',
    nomor_peminjaman: '0003/BSKJI.1/RT/RR/VIII/2026',
    user_id: 'usr_peminjam_01',
    peminjam_nama: 'Budi Santoso',
    peminjam_nip: '19850315 200801 1 002',
    peminjam_jabatan: 'Analis Kebijakan Ahli Muda',
    unit_id: 'unit_program',
    unit_nama: 'Bagian Program dan Evaluasi',
    room_id: 'room_industri_hijau',
    room_nama: 'Ruang Industri Hijau',
    keperluan: 'Rapat Persiapan Kunjungan Kerja Sekretaris Jenderal Kemenperin',
    tanggal: '2026-08-14',
    jam_mulai: '10:00',
    jam_selesai: '12:00',
    durasi: '2 Jam',
    jumlah_peserta: 22,
    keterangan: 'Peserta Eselon II dan Eselon III. Butuh catering transit.',
    status: 'MENUNGGU_PERSETUJUAN_KABAG',
    approvals: [
      {
        id: 'app_003_1',
        booking_id: 'bk_003',
        approver_id: 'usr_koordinator_01',
        approver_nama: 'Siti Rahma',
        approver_nip: '19820420 200604 2 003',
        approver_jabatan: 'Koordinator Urusan Internal dan Ruang Rapat',
        level_approval: 'KOORDINATOR',
        status: 'DISETUJUI',
        catatan: 'Ketersediaan ruangan sudah terkonfirmasi.',
        approved_at: '2026-08-11T10:15:00Z',
      },
    ],
    created_at: '2026-08-11T09:30:00Z',
    updated_at: '2026-08-11T10:15:00Z',
  },
  {
    id: 'bk_004',
    nomor_peminjaman: '0004/BSKJI.1/RT/RR/VIII/2026',
    user_id: 'usr_peminjam_01',
    peminjam_nama: 'Budi Santoso',
    peminjam_nip: '19850315 200801 1 002',
    peminjam_jabatan: 'Analis Kebijakan Ahli Muda',
    unit_id: 'unit_program',
    unit_nama: 'Bagian Program dan Evaluasi',
    room_id: 'room_standar',
    room_nama: 'Ruang Standar',
    keperluan: 'Sosialisasi Sistem Akuntabilitas Kinerja Instansi Pemerintah (SAKIP)',
    tanggal: '2026-08-15',
    jam_mulai: '08:30',
    jam_selesai: '11:30',
    durasi: '3 Jam',
    jumlah_peserta: 18,
    keterangan: 'Audience dari seluruh bagian Sekretariat BSKJI.',
    status: 'MENUNGGU_PERSETUJUAN_KABAG',
    approvals: [
      {
        id: 'app_004_1',
        booking_id: 'bk_004',
        approver_id: 'usr_koordinator_01',
        approver_nama: 'Siti Rahma',
        approver_nip: '19820420 200604 2 003',
        approver_jabatan: 'Koordinator Urusan Internal dan Ruang Rapat',
        level_approval: 'KOORDINATOR',
        status: 'DISETUJUI',
        catatan: 'Fasilitas projector dan audio sistem siap disetting.',
        approved_at: '2026-08-11T13:30:00Z',
      },
    ],
    created_at: '2026-08-11T10:00:00Z',
    updated_at: '2026-08-11T13:30:00Z',
  },
  {
    id: 'bk_005',
    nomor_peminjaman: '0005/BSKJI.1/RT/RR/VIII/2026',
    user_id: 'usr_peminjam_01',
    peminjam_nama: 'Budi Santoso',
    peminjam_nip: '19850315 200801 1 002',
    peminjam_jabatan: 'Analis Kebijakan Ahli Muda',
    unit_id: 'unit_program',
    unit_nama: 'Bagian Program dan Evaluasi',
    room_id: 'room_inovatif',
    room_nama: 'Ruang Inovatif',
    keperluan: 'Evaluasi Vendor Pengadaan Perangkat IT',
    tanggal: '2026-08-08',
    jam_mulai: '10:00',
    jam_selesai: '11:30',
    durasi: '1 Jam 30 Menit',
    jumlah_peserta: 8,
    keterangan: 'Ditolak karena berbenturan jadwal internal pimpinan.',
    status: 'DITOLAK_KOORDINATOR',
    approvals: [
      {
        id: 'app_005_1',
        booking_id: 'bk_005',
        approver_id: 'usr_koordinator_01',
        approver_nama: 'Siti Rahma',
        approver_nip: '19820420 200604 2 003',
        approver_jabatan: 'Koordinator Urusan Internal dan Ruang Rapat',
        level_approval: 'KOORDINATOR',
        status: 'DITOLAK',
        catatan: 'Mohon dijadwalkan ulang di hari lain karena ada rapat pimpinan mendadak.',
        approved_at: '2026-08-08T08:00:00Z',
      },
    ],
    created_at: '2026-08-07T14:00:00Z',
    updated_at: '2026-08-08T08:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_001',
    user_id: 'usr_peminjam_01',
    booking_id: 'bk_001',
    judul: 'Pengajuan Disetujui Akhir',
    pesan: 'Pengajuan peminjaman 0001/BSKJI.1/RT/RR/VIII/2026 untuk Ruang Sinergi telah disetujui akhir oleh Kepala Bagian Umum.',
    status_baca: false,
    created_at: '2026-08-10T13:00:00Z',
  },
  {
    id: 'notif_002',
    user_id: 'usr_koordinator_01',
    booking_id: 'bk_002',
    judul: 'Pengajuan Baru Menunggu Verifikasi',
    pesan: 'Budi Santoso mengajukan peminjaman Ruang Digital untuk tanggal 13 Agustus 2026.',
    status_baca: false,
    created_at: '2026-08-11T09:00:00Z',
  },
  {
    id: 'notif_003',
    user_id: 'usr_koordinator_01',
    booking_id: 'bk_003',
    judul: 'Pengajuan Masuk Verifikasi Koordinator',
    pesan: 'Pengajuan 0003/BSKJI.1/RT/RR/VIII/2026 membutuhkan verifikasi ketersediaan ruang.',
    status_baca: false,
    created_at: '2026-08-11T10:15:00Z',
  },
  {
    id: 'notif_004',
    user_id: 'usr_kabag_01',
    booking_id: 'bk_003',
    judul: 'Pengajuan Menunggu Persetujuan Akhir',
    pesan: 'Pengajuan 0003/BSKJI.1/RT/RR/VIII/2026 telah diverifikasi Koordinator dan menunggu persetujuan akhir Kabag Umum.',
    status_baca: false,
    created_at: '2026-08-11T10:20:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud_001',
    user_id: 'usr_peminjam_01',
    user_nama: 'Budi Santoso',
    role: 'Peminjam',
    aktivitas: 'Membuat Pengajuan Peminjaman Ruang',
    booking_id: 'bk_001',
    nomor_peminjaman: '0001/BSKJI.1/RT/RR/VIII/2026',
    data_lama: '-',
    data_baru: 'Status: MENUNGGU_PERSETUJUAN_KOORDINATOR',
    timestamp: '2026-08-10T08:30:00Z',
    ip_address: '10.14.22.105',
  },
  {
    id: 'aud_003',
    user_id: 'usr_koordinator_01',
    user_nama: 'Siti Rahma',
    role: 'Koordinator Ruang Rapat',
    aktivitas: 'Verifikasi Ketersediaan Ruangan Stage 1',
    booking_id: 'bk_001',
    nomor_peminjaman: '0001/BSKJI.1/RT/RR/VIII/2026',
    data_lama: 'Status: MENUNGGU_PERSETUJUAN_KOORDINATOR',
    data_baru: 'Status: MENUNGGU_PERSETUJUAN_KABAG',
    timestamp: '2026-08-10T10:20:00Z',
    ip_address: '10.14.22.120',
  },
  {
    id: 'aud_004',
    user_id: 'usr_kabag_01',
    user_nama: 'Agus Setiawan',
    role: 'Kepala Bagian Umum',
    aktivitas: 'Persetujuan Akhir dan Lock Reservasi Ruang Stage 2',
    booking_id: 'bk_001',
    nomor_peminjaman: '0001/BSKJI.1/RT/RR/VIII/2026',
    data_lama: 'Status: MENUNGGU_PERSETUJUAN_KABAG',
    data_baru: 'Status: DISETUJUI',
    timestamp: '2026-08-10T13:00:00Z',
    ip_address: '10.14.22.101',
  },
];
